start =
	expression

expression =
	atom
	/
	open optional_space first:expression rest:space_and_expression* optional_space close  
	{ return [first].concat(rest) }

space_and_expression = 
	space optional_space left:expression
	{ return left }

open = 
	"("

close = 
	")"

optional_space =
	space*

space =
	" "

validchar
	= [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =
	chars:validchar+
	{ return chars.join(""); }